{% set version = "2.5.3" %}

package:
  name: pdal
  version: {{ version }}

source:
  url: https://github.com/PDAL/PDAL/releases/download/{{ version }}/PDAL-{{ version }}-src.tar.bz2
  sha256: 1d193e9cf11766a394722e1899d6a7d1fb81387af113250beff58e6325851b13

build:
  number: 0
  # geotiff, libgdal=3.0, ceres-solver (and its dependencies suitesparse, gflags, glog, eigen) are not available on s390x
  skip: true  # [s390x]
  run_exports:
    - {{ pin_subpackage('pdal', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
    - libcxx =14  # [osx]

  host:
    - blas  # [win]
    - mkl  # [win]
    - ceres-solver 2.1.0
    - curl
    - draco
    - eigen 3.3.7
    - geotiff 1.7.0
    - hdf5 1.10.6              # [not (osx and arm64)]
    - hdf5 1.12.1              # [osx and arm64]
    - libgdal 3.0.2
    - libkml 1.3.0
    - libpq 12.9
    - libxml2
    - nitro
    - numpy {{ numpy }}
    - openssl 1.1.1
    - sqlite
    - tiledb 2.3.3
    - xz
    - zlib 1.2.13
    - zstd 1.5.2
  run:
    - blas  # [win]
    - mkl   # [win]
    - ceres-solver >=2.1.0,<2.2.0a0
    - curl
    - draco
    - eigen >=3.3.7,<3.3.8.0a0
    - geotiff >=1.7.0,<1.8.0a0
    - hdf5 >=1.10.6,<1.10.7.0a0  # [not (osx and arm64)]
    - hdf5 >=1.12.1,<1.12.2.0a0  # [osx and arm64]
    - libgdal >=3.0.2,<3.1.0a0
    - libkml >=1.3.0,<1.4.0a0
    - libpq >=12.9,<13.0a0
    - libxml2
    - nitro
    - {{ pin_compatible('numpy') }}
    - openssl >=1.1.1t,<1.1.2a
    - sqlite
    - tiledb >=2.3.3,<2.4.0a0
    - xz
    - zlib >=1.2.13,<1.3.0a0
    - zstd >=1.5.2,<1.6.0a0
  run_constrained:   # [osx and x86_64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - pdal --version
    - pdal --drivers --debug

about:
  home: https://pdal.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL)
  description: Point cloud data processing.
  doc_url: https://pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
