{% set version = "2.5.3" %}

package:
  name: pdal
  version: {{ version }}

source:
  url: https://github.com/PDAL/PDAL/releases/download/{{ version }}/PDAL-{{ version }}-src.tar.bz2
  sha256: 1d193e9cf11766a394722e1899d6a7d1fb81387af113250beff58e6325851b13

build:
  number: 0
  # geotiff, libgdal=3.0, ceres-solver (and its dependencies suitesparse, gflags, glog, eigen) are not available on s390x
  skip: true  # [s390x]
  run_exports:
    - {{ pin_subpackage('pdal', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make        # [not win]
    - pkg-config
    - libcxx =14  # [osx]

  host:
    - blas  # [win]
    - mkl  # [win]
    - ceres-solver
    - curl
    - draco
    - eigen
    - geotiff
    - hdf5
    - libgdal
    - libkml
    - libpq
    - libxml2
    - nitro
    - openssl
    - tiledb
    - zlib
    - zstd
  run:
    - blas  # [win]
    - mkl   # [win]
    - ceres-solver
    - curl
    - draco
    - eigen
    - geotiff
    - hdf5
    - libgdal
    - libkml
    - libpq
    - libxml2
    - nitro
    - openssl
    - tiledb
    - zlib
    - zstd
  run_constrained:   # [osx and x86_64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - pdal --version
    - pdal --drivers --debug

about:
  home: https://pdal.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL)
  description: Point cloud data processing.
  doc_url: https://pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
