travis:
  secure:
    BINSTAR_TOKEN: EhydhTVGgPiJ2KoZ6xxl//aSdEgtmH7HrZIZzKBPRzulGl656+YM6S9vvVwinrlfpUI83uC2+u4r3MwqIOiNMPhg9a3tg9i4dzYt2RjVBDFk0r4SC7/D9LrILyk0+2pZ052V7r7cHccucc3dI7BHe3tgJDK87Mo47s2NtY1azQwIag1VC9hTjtj2j+/odlpUd6VK251VyK3k7zeHyt+pSVRMWNsfjVuLMdKDjqI68AAq+hrgUQjWlIHYXQIQygGKWm036aQzU88wuUA6svANmeNibm3S36N3F7m9iQs0YyQxqeyASVrqMlp8n/HtCfFeyZwdsZMdW17ur8wPJ3V1FLUSLeHS8wlRM0CftVS12zAP42tAHNZ2c+c2lXFi1hFvH9jryVy7HFiaENg1hAtusjtq4hueGloxlkX2uVl0UJSqqrFDyPvKmtczz/eaxrb9dxlWEdzUDwozafSseH0t0UzHRit/tBvlvNtzTitkBc3mwzKqrZ/87MiJRb1mBpHjKDWcrqh4BiZ1J8Po/yS1KPjahug1uKTLYHTBun5AwET5sqSP5NZeky/kYhzHt6PU5uDgx03yVnYYXil97PXsyRM6dnEalYMNCTG1lXD3gp+A0re6NOiH0DmP6zZ7sqwrc7nieDRGzxZY0BSVq92S/sjpRIF8DTjBCBpkujo8M88=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
