travis:
  secure:
    BINSTAR_TOKEN: YJVfLpqqIsdFN2FVJZ4nKK1V/4bNX+ddyRKxeQik8aG3CqdCKCPOdRSP00Bq1jsiTnu7rveJXu27LkH6g1C99lrao482mby8xElKhGa+y97Yo370/GQuwDTtppxjkMtj4EKpqWXogR/q5DthFS0khd/WZNqt1+l2WOdwpXDZJiD4KUVpvcmUQQkd5xr2v5U5TMvMW0oIKSQEJmbUnku+wbSOfb0AGaQbFAlrb5on6V79LIOQctrGqgOMKaKN1EX5keqjYsncSyYZmLMS+ZoD8nD53y5l4kpRGZdBshUG3vs1/tNT7ju+g855qoE9Qr5mVkVkzqBNBDpn57T2csnrN/ezjA0CvLFzQrqyqNAlUtsGyg78SYYBD4T60rO8Wl5w6GDPT1dmaBZmXigdhms2NKLAOHVsuiAPIkTddmblgSgV3d/cGhvYx0Y9PVPRWCLTcTTpOhXeY9IMDm8lnb9cuq0CCLDlrVZz979L0lGJOV74Il+2JbbHHRQPcLlSxCrAJpJHDWsP+H3T/6sXUDlousrRRa5e71xOLBr9R89OfKieNrcvHYkHyiziW/lLx5/BAaB78PYKiuhcQIVjVbIM4jl7Dwonh6GFFx9HYsIPQCeGBPRT4WrEERSRGqzwvuQO1KFasHNkM/RGjbfRtZ4yPRcl7cQP07CvmSZi77vLmfA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
