travis:
  secure:
    BINSTAR_TOKEN: fm8LmNPS+gO9PrMGKWd21y3ngRNP2ihtsSsLngMxNf7obb690CmG8pGNaw0JkLAUVnb6nw612QP83CSiT26DCALH14JPqeIyqYzNKYGAdFmfVg74BW/B8zXmu0uHdEuatO4mtM2BDEngrcHPi8r6to5zQnrIPVeLmpk1tQN2YE36ZWP+jUmKkxXJuwiXW9bPOGntagITuVrA5xG2BBmD1Vh855LwTXVdL49iV3ROOCTxu/hF0V154jxVhSmAYAAs49urwc7HxxlHpYzfDL9sHbrHf7c1G3ffmz0zUHM4K6hvo1SOUVomSAHckyAREua5/8L4Dpi65J/toGI18O2T0H2XCEIrwe7oZ7KoSfOJSf3bfEYXIkUigefn/FB4EsekG68qzTVG668XASTPWZg+MQOZvqUgkDjnLWG57lDteJYBsL52pyZPNNu+LU37mALYTM6x4oi+YpevotJ7em5rgeb+eW8BzCjnlVXb6FcFLtUfS3+5NpzEAkGE0UEun0sI4569YapXsxXcDVC6OIj6wmoIYfybvMFTdf8fGO/AO661odC675zqEeoIFFIuDjuT9+twPrRfXe2KvR/Nd67BulYbf7XDoeJe81qEp/3OUil8j9+Hqd5VsElalcwHeAg9689+ARkLKJa6TFiyZxzzoeBJiDtL6GoBaNUkS4J5qDs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
